CCM Website/CCM Website/Areas/Admin/Controllers/LearningPlatformController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCM_Website.Data;
using CCM_Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Extensions;

namespace CCM_Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LearningPlatformController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LearningPlatformController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/LearningPlatform
        public Task<IActionResult> Index(string searchString, int? page)
        {
            var learningPlatform = _context.LearningPlatforms.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                learningPlatform = learningPlatform.Where(l =>
                    l.PlatformName.ToLower().Contains(searchString.ToLower())
                );
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;

            var pagedLearningPlatform = learningPlatform.ToPagedList(pageNumber, pageSize);
            return Task.FromResult<IActionResult>(View(pagedLearningPlatform));
        }

        // GET: Admin/LearningPlatform/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learningPlatform = await _context.LearningPlatforms.FirstOrDefaultAsync(m =>
                m.PlatformId == id
            );
            if (learningPlatform == null)
            {
                return NotFound();
            }

            return View(learningPlatform);
        }

        // GET: Admin/LearningPlatform/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/LearningPlatform/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("PlatformId,PlatformName")] LearningPlatform learningPlatform
        )
        {
            try
            {
                learningPlatform.Workbooks = new List<Workbook>();
                learningPlatform.LearningPlatformActivities =
                    new List<LearningPlatformActivities>();
            }
            catch (Exception e)
            {
                Console.WriteLine($"Model Creation Error: {e.Message}");
                ModelState.AddModelError(
                    "",
                    "An error occurred while saving the workbook. Please try again later."
                );
                return View(learningPlatform);
            }

            ModelState.Remove(nameof(learningPlatform.Workbooks));
            ModelState.Remove(nameof(learningPlatform.LearningPlatformActivities));

            if (!ModelState.IsValid)
            {
                Console.WriteLine("Error creating model");
                return View(learningPlatform);
            }

            try
            {
                _context.Add(learningPlatform);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception exp)
            {
                Console.WriteLine($"Model Creation Error: {exp.Message}");
                ModelState.AddModelError(
                    "",
                    "An error occurred while saving the workbook. Please try again later."
                );
                return View(learningPlatform);
            }
        }

        // GET: Admin/LearningPlatform/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learningPlatform = await _context.LearningPlatforms.FindAsync(id);
            if (learningPlatform == null)
            {
                return NotFound();
            }
            return View(learningPlatform);
        }

        // POST: Admin/LearningPlatform/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("PlatformId,PlatformName")] LearningPlatform learningPlatform
        )
        {
            if (id != learningPlatform.PlatformId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(learningPlatform);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LearningPlatformExists(learningPlatform.PlatformId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(learningPlatform);
        }

        // GET: Admin/LearningPlatform/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var learningPlatform = await _context.LearningPlatforms.FirstOrDefaultAsync(m =>
                m.PlatformId == id
            );
            if (learningPlatform == null)
            {
                return NotFound();
            }

            return View(learningPlatform);
        }

        // POST: Admin/LearningPlatform/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var learningPlatform = await _context.LearningPlatforms.FindAsync(id);
            if (learningPlatform != null)
            {
                _context.LearningPlatforms.Remove(learningPlatform);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LearningPlatformExists(int id)
        {
            return _context.LearningPlatforms.Any(e => e.PlatformId == id);
        }
    }
}

CCM Website/CCM Website/Areas/Admin/Views/LearningPlatform/Create.cshtml
@model CCM_Website.Models.LearningPlatform

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="LearningPlatform" asp-action="Index">Learning Platform</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Create Learning Platform</h2></div>
</div>

<hr />
@Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>
            <div class="form-group">
                <label asp-for="PlatformName" class="control-label">Platform Name</label>
                <input asp-for="PlatformName" class="form-control" />
                <span asp-validation-for="PlatformName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>
<br/>

CCM Website/CCM Website/Areas/Admin/Views/LearningPlatform/Delete.cshtml
@model CCM_Website.Models.LearningPlatform

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="LearningPlatform" asp-action="Index">Learning Platform</a></li>
            <li class="breadcrumb-item active" aria-current="page">Delete</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Delete Learning Platform</h2></div>
    <hr />
</div>

    <dl class="row">
        <dt class = "col-sm-2">
            Platform Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlatformName)
        </dd>
    </dl>

    <form asp-action="Delete" class="d-flex gap-2">
        <input type="hidden" asp-for="PlatformId" />
        <a class="btn btn-danger" id="deleteB">Delete</a>
        <input type="submit" value="Confirm" class="btn btn-danger d-none" id="confirm"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </form>


<script>

    var deleteB = document.getElementById("deleteB")
    var confirm = document.getElementById("confirm")

    deleteB.onclick = function(){
        deleteB.className = "btn btn-danger d-none"
        confirm.className = "btn btn-danger d-block"
    }
</script>

CCM Website/CCM Website/Areas/Admin/Views/LearningPlatform/Details.cshtml
@model CCM_Website.Models.LearningPlatform

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="LearningPlatform" asp-action="Index">Learning Platform</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Learning Platform Details</h2></div>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Platform Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlatformName)
        </dd>
    </dl>
</div>

CCM Website/CCM Website/Areas/Admin/Views/LearningPlatform/Edit.cshtml
@model CCM_Website.Models.LearningPlatform

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="LearningPlatform" asp-action="Index">Learning Platform</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Edit Learning Platform</h2></div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PlatformId" />
            <div class="form-group">
                <label asp-for="PlatformName" class="control-label">Platform Name</label>
                <input asp-for="PlatformName" class="form-control" />
                <span asp-validation-for="PlatformName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

CCM Website/CCM Website/Areas/Admin/Views/LearningPlatform/Index.cshtml
@model X.PagedList.IPagedList<CCM_Website.Models.LearningPlatform>
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using X.PagedList.Mvc;
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Learning Platform";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active" aria-current="page">Learning Platform</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3">
    <div class="col d-flex justify-content-between align-items-center">
        <h2>Learning Platforms</h2>
        <a class="btn btn-success"
           asp-action="Create">Create New Learning Platform
        </a>
    </div>
</div>

<div class="row my-3">
    <div class="col d-flex justify-content-start align-items-center">
        @using (Html.BeginForm("Index", "LearningPlatform", FormMethod.Get))
        {
            <div class="input-group">
                @Html.TextBox("searchString", ViewData["SearchString"] as string, new { @class = "form-control", placeholder = "Search platform name..." })
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        }
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
               Platform Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlatformName)
            </td>
            <td>
                <div class="d-flex justify-content-end gap-2">
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.PlatformId">Edit</a>
                    <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.PlatformId">Details</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.PlatformId">Delete</a>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>


<br />
@Html.PagedListPager(Model,
    page => Url.Action("Index", new { page, searchString = ViewData["SearchString"] }),
    new PagedListRenderOptions
    {
        MaximumPageNumbersToDisplay = 3,
        DisplayLinkToFirstPage = (Model.PageNumber <= 2) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always, 
        DisplayLinkToLastPage = (Model.PageNumber >= Model.PageCount - 1) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Never, 
        DisplayLinkToNextPage = PagedListDisplayMode.Never,  
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,  
        UlElementClasses = new[] { "pagination" },
        LiElementClasses = new[] { "page-item" }, 
        PageClasses = new[] { "page-link" } 
    }
)