CCM Website/CCM Website/Models/TaskProgressStatus.cs
using System.ComponentModel.DataAnnotations;

namespace CCM_Website.Models
{
    public class TaskProgressStatus
    {
        [Key]
        public int StatusId { get; set; }

        public required string StatusName { get; set; }

        [RegularExpression("^#(?:[0-9a-fA-F]{3}){1,2}$", ErrorMessage = "Invalid hex colour code")]
        public string? StatusColour { get; set; }

        [RegularExpression("^#(?:[0-9a-fA-F]{3}){1,2}$", ErrorMessage = "Invalid hex colour code")]
        public string? StatusTextColour { get; set; }
    }
}

CCM Website/CCM Website/Areas/Admin/Controllers/TaskProgressStatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCM_Website.Data;
using CCM_Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Extensions;

namespace CCM_Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TaskProgressStatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TaskProgressStatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/TaskProgressStatus
        public Task<IActionResult> Index(string searchString, int? page)
        {
            var taskProgressStatus = _context.TaskProgressStatus.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                taskProgressStatus = taskProgressStatus.Where(t =>
                    t.StatusName.ToLower().Contains(searchString.ToLower())
                );
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;

            ViewData["SearchString"] = searchString;

            var pagedTaskProgressStatus = taskProgressStatus.ToPagedList(pageNumber, pageSize);
            return Task.FromResult<IActionResult>(View(pagedTaskProgressStatus));
        }

        // GET: Admin/TaskProgressStatus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskProgressStatus = await _context.TaskProgressStatus.FirstOrDefaultAsync(m =>
                m.StatusId == id
            );
            if (taskProgressStatus == null)
            {
                return NotFound();
            }

            return View(taskProgressStatus);
        }

        // GET: Admin/TaskProgressStatus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/TaskProgressStatus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("StatusName,StatusColour,StatusTextColour")] TaskProgressStatus taskProgressStatus
        )
        {
            if (ModelState.IsValid)
            {
                _context.Add(taskProgressStatus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(taskProgressStatus);
        }

        // GET: Admin/TaskProgressStatus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskProgressStatus = await _context.TaskProgressStatus.FindAsync(id);
            if (taskProgressStatus == null)
            {
                return NotFound();
            }
            return View(taskProgressStatus);
        }

        // POST: Admin/TaskProgressStatus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("StatusId,StatusName,StatusColour,StatusTextColour")]
                TaskProgressStatus taskProgressStatus
        )
        {
            if (id != taskProgressStatus.StatusId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(taskProgressStatus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TaskProgressStatusExists(taskProgressStatus.StatusId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(taskProgressStatus);
        }

        // GET: Admin/TaskProgressStatus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var taskProgressStatus = await _context.TaskProgressStatus.FirstOrDefaultAsync(m =>
                m.StatusId == id
            );
            if (taskProgressStatus == null)
            {
                return NotFound();
            }

            return View(taskProgressStatus);
        }

        // POST: Admin/TaskProgressStatus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var taskProgressStatus = await _context.TaskProgressStatus.FindAsync(id);
            if (taskProgressStatus != null)
            {
                _context.TaskProgressStatus.Remove(taskProgressStatus);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TaskProgressStatusExists(int id)
        {
            return _context.TaskProgressStatus.Any(e => e.StatusId == id);
        }
    }
}

CCM Website/CCM Website/Areas/Admin/Views/TaskProgressStatus/Create.cshtml
@model CCM_Website.Models.TaskProgressStatus

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="TaskProgressStatus" asp-action="Index">Task Progress Status</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Create Task Status</h2></div>
</div>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StatusName" class="control-label">Progress Status</label>
                <input asp-for="StatusName" class="form-control" />
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusColour" class="control-label">Status Colour</label>
                <input asp-for="StatusColour" class="form-control" />
                <span asp-validation-for="StatusColour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusTextColour" class="control-label">Status Text Colour</label>
                <input asp-for="StatusTextColour" class="form-control" />
                <span asp-validation-for="StatusTextColour" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

CCM Website/CCM Website/Areas/Admin/Views/TaskProgressStatus/Delete.cshtml
@model CCM_Website.Models.TaskProgressStatus

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="TaskProgressStatus" asp-action="Index">Task Progess Status</a></li>
            <li class="breadcrumb-item active" aria-current="page">Delete</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Delete Task Status</h2></div>
    <hr />
</div>


<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Progress Status
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
    </dl>

    <form asp-action="Delete" class="d-flex gap-2">
        <input type="hidden" asp-for="StatusId" />
        <a class="btn btn-danger" id="deleteB">Delete</a>
        <input type="submit" value="Confirm" class="btn btn-danger d-none" id="confirm"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </form>
</div>

<script>

    var deleteB = document.getElementById("deleteB")
    var confirm = document.getElementById("confirm")

    deleteB.onclick = function(){
        deleteB.className = "btn btn-danger d-none"
        confirm.className = "btn btn-danger d-block"
    }
</script>

CCM Website/CCM Website/Areas/Admin/Views/TaskProgressStatus/Details.cshtml
@model CCM_Website.Models.TaskProgressStatus

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="TaskProgressStatus" asp-action="Index">Task Progress Status</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Task Status Details</h2></div>
</div>


<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Progress Status
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusName)
        </dd>
        <dt class = "col-sm-2">
            Status Colour
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusColour)
        </dd>
        <dt class = "col-sm-2">
            Status Text Colour
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusTextColour)
        </dd>
    </dl>
</div>

CCM Website/CCM Website/Areas/Admin/Views/TaskProgressStatus/Edit.cshtml
@model CCM_Website.Models.TaskProgressStatus

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="TaskProgressStatus" asp-action="Index">Task Progress Status</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Edit Task Status</h2></div>
</div>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StatusId" />
            <div class="form-group">
                <label asp-for="StatusName" class="control-label">Progress Status</label>
                <input asp-for="StatusName" class="form-control" />
                <span asp-validation-for="StatusName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusColour" class="control-label">Status Colour</label>
                <input asp-for="StatusColour" class="form-control" />
                <span asp-validation-for="StatusColour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StatusTextColour" class="control-label">Status Text Colour</label>
                <input asp-for="StatusTextColour" class="form-control" />
                <span asp-validation-for="StatusTextColour" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

CCM Website/CCM Website/Areas/Admin/Views/TaskProgressStatus/Index.cshtml
@model X.PagedList.IPagedList<CCM_Website.Models.TaskProgressStatus>
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Task Progress Status";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active" aria-current="page">Task Progress Status</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3">
    <div class="col d-flex justify-content-between align-items-center">
        <h2>Task Progress Status'</h2>
        <a class="btn btn-success"
           asp-action="Create">Create New Task Status
        </a>
    </div>
</div>

<div class="row my-3">
    <div class="col d-flex justify-content-start align-items-center">
        @using (Html.BeginForm("Index", "TaskProgressStatus", FormMethod.Get))
        {
            <div class="input-group">
                @Html.TextBox("searchString", ViewData["SearchString"] as string, new { @class = "form-control", placeholder = "Search progress status..." })
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        }
    </div>
</div>

<table class="table">
    <thead>
    <tr>
        <th>
            Progress Status
        </th>
        <th>
            Progress Status Colour
        </th>
        <th>
            Progress Status Text Colour
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StatusName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusColour)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StatusTextColour)
            </td>
            <td>
                <div class="d-flex flex-wrap justify-content-end gap-2">
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.StatusId">Edit</a>
                    <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.StatusId">Details</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.StatusId">Delete</a>
                </div>
            </td>
        </tr>
    }
    </tbody>
</table>


<br />
@Html.PagedListPager(Model,
    page => Url.Action("Index", new { page, searchString = ViewData["SearchString"] }),
    new PagedListRenderOptions
    {
        MaximumPageNumbersToDisplay = 3,
        DisplayLinkToFirstPage = (Model.PageNumber <= 2) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always, 
        DisplayLinkToLastPage = (Model.PageNumber >= Model.PageCount - 1) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Never, 
        DisplayLinkToNextPage = PagedListDisplayMode.Never,  
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,  
        UlElementClasses = new[] { "pagination" },
        LiElementClasses = new[] { "page-item" }, 
        PageClasses = new[] { "page-link" } 
    }
)