CCM Website/CCM Website/Models/UniversityArea.cs
using System.ComponentModel.DataAnnotations;

namespace CCM_Website.Models
{
    public class UniversityArea
    {
        [Key]
        public int AreaId { get; set; }

        public required string AreaName { get; set; }
    }
}

CCM Website/CCM Website/Areas/Admin/Controllers/UniversityAreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCM_Website.Data;
using CCM_Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using X.PagedList.Extensions;

namespace CCM_Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UniversityAreaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UniversityAreaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Admin/UniversityArea
        public Task<IActionResult> Index(string searchString, int? page)
        {
            var universityArea = _context.UniversityArea.AsQueryable();

            if (!string.IsNullOrEmpty(searchString))
            {
                universityArea = universityArea.Where(uA =>
                    uA.AreaName.ToLower().Contains(searchString.ToLower())
                );
            }

            int pageSize = 10;
            int pageNumber = page ?? 1;

            ViewData["SearchString"] = searchString;

            var pagedUniversityArea = universityArea.ToPagedList(pageNumber, pageSize);
            return Task.FromResult<IActionResult>(View(pagedUniversityArea));
        }

        // GET: Admin/UniversityArea/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universityArea = await _context.UniversityArea.FirstOrDefaultAsync(m =>
                m.AreaId == id
            );
            if (universityArea == null)
            {
                return NotFound();
            }

            return View(universityArea);
        }

        // GET: Admin/UniversityArea/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/UniversityArea/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("AreaId,AreaName")] UniversityArea universityArea
        )
        {
            if (ModelState.IsValid)
            {
                _context.Add(universityArea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(universityArea);
        }

        // GET: Admin/UniversityArea/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universityArea = await _context.UniversityArea.FindAsync(id);
            if (universityArea == null)
            {
                return NotFound();
            }
            return View(universityArea);
        }

        // POST: Admin/UniversityArea/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(
            int id,
            [Bind("AreaId,AreaName")] UniversityArea universityArea
        )
        {
            if (id != universityArea.AreaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(universityArea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UniversityAreaExists(universityArea.AreaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(universityArea);
        }

        // GET: Admin/UniversityArea/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var universityArea = await _context.UniversityArea.FirstOrDefaultAsync(m =>
                m.AreaId == id
            );
            if (universityArea == null)
            {
                return NotFound();
            }

            return View(universityArea);
        }

        // POST: Admin/UniversityArea/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var universityArea = await _context.UniversityArea.FindAsync(id);
            if (universityArea != null)
            {
                _context.UniversityArea.Remove(universityArea);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UniversityAreaExists(int id)
        {
            return _context.UniversityArea.Any(e => e.AreaId == id);
        }
    }
}

CCM Website/CCM Website/Areas/Admin/Views/UniversityArea/Create.cshtml
@model CCM_Website.Models.UniversityArea

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="UniversityArea" asp-action="Index">Workbook Area</a></li>
            <li class="breadcrumb-item active" aria-current="page">Create</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Create Workbook Area</h2></div>
</div>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AreaName" class="control-label">Area Name</label>
                <input asp-for="AreaName" class="form-control" />
                <span asp-validation-for="AreaName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

CCM Website/CCM Website/Areas/Admin/Views/UniversityArea/Delete.cshtml
@model CCM_Website.Models.UniversityArea

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="UniversityArea" asp-action="Index">Workbook Area</a></li>
            <li class="breadcrumb-item active" aria-current="page">Delete</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Delete Workbook Area</h2></div>
    <hr />
</div>

<div>
    <dl class="row">
        <dt class = "col-sm-2">
            Area Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AreaName)
        </dd>
    </dl>

    <form asp-action="Delete" class="d-flex gap-2">
        <input type="hidden" asp-for="AreaId" />
        <a class="btn btn-danger" id="deleteB">Delete</a>
        <input type="submit" value="Confirm" class="btn btn-danger d-none" id="confirm"/>
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </form>
</div>

<script>

    var deleteB = document.getElementById("deleteB")
    var confirm = document.getElementById("confirm")

    deleteB.onclick = function(){
        deleteB.className = "btn btn-danger d-none"
        confirm.className = "btn btn-danger d-block"
    }
</script>

CCM Website/CCM Website/Areas/Admin/Views/UniversityArea/Details.cshtml
@model CCM_Website.Models.UniversityArea

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="UniversityArea" asp-action="Index">Workbook Area</a></li>
            <li class="breadcrumb-item active" aria-current="page">Details</li>
        </div>
    </ol>
    <hr/>
</nav>


<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Workbook Area Details</h2></div>
</div>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Area Name
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AreaName)
        </dd>
    </dl>
</div>

CCM Website/CCM Website/Areas/Admin/Views/UniversityArea/Edit.cshtml
@model CCM_Website.Models.UniversityArea

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="UniversityArea" asp-action="Index">Workbook Area</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3 align-items-start">
    <div class="col-md-10"><h2>Edit Workbook Area</h2></div>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AreaId" />
            <div class="form-group">
                <label asp-for="AreaName" class="control-label">Area Name</label>
                <input asp-for="AreaName" class="form-control" />
                <span asp-validation-for="AreaName" class="text-danger"></span>
            </div>
            <br/>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a class="btn btn-secondary" asp-action="Index">Cancel</a>
            </div>
        </form>
    </div>
</div>

CCM Website/CCM Website/Areas/Admin/Views/UniversityArea/Index.cshtml
@model X.PagedList.IPagedList<CCM_Website.Models.UniversityArea>
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using X.PagedList.Mvc.Core
@{
    ViewData["Title"] = "Workbook Area";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb d-flex justify-content-start">
        <li><button class="btn btn-primary me-3" onclick="history.back();">Back</button></li>
        <div class="d-flex m-2">
            <li class="breadcrumb-item"><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
            <li class="breadcrumb-item active" aria-current="page">Workbook Area</li>
        </div>
    </ol>
    <hr/>
</nav>

<div class="row my-3">
    <div class="col d-flex justify-content-between align-items-center">
        <h2>Workbook Areas</h2>
        <a class="btn btn-success"
           asp-action="Create">Create Workbook Area
        </a>
    </div>
</div>

<div class="row my-3">
    <div class="col d-flex justify-content-start align-items-center">
        @using (Html.BeginForm("Index", "UniversityArea", FormMethod.Get))
        {
            <div class="input-group">
                @Html.TextBox("searchString", ViewData["SearchString"] as string, new { @class = "form-control", placeholder = "Search area name..." })
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        }
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Area Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AreaName)
            </td>
            <td>
                <div class="d-flex flex-wrap justify-content-end gap-2">
                    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.AreaId">Edit</a>
                    <a class="btn btn-secondary" asp-action="Details" asp-route-id="@item.AreaId">Details</a>
                    <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.AreaId">Delete</a>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

@Html.PagedListPager(Model,
    page => Url.Action("Index", new { page, searchString = ViewData["SearchString"] }),
    new PagedListRenderOptions
    {
        MaximumPageNumbersToDisplay = 3,
        DisplayLinkToFirstPage = (Model.PageNumber <= 2) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always, 
        DisplayLinkToLastPage = (Model.PageNumber >= Model.PageCount - 1) ? PagedListDisplayMode.Never : PagedListDisplayMode.Always,
        DisplayLinkToPreviousPage = PagedListDisplayMode.Never, 
        DisplayLinkToNextPage = PagedListDisplayMode.Never,  
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,  
        UlElementClasses = new[] { "pagination" },
        LiElementClasses = new[] { "page-item" }, 
        PageClasses = new[] { "page-link" } 
    }
)